// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_login from "./routes/api/login.ts";
import * as $index from "./routes/index.tsx";
import * as $login from "./routes/login.tsx";
import * as $middleware from "./routes/middleware.tsx";
import * as $xata from "./islands/xata.ts";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/login.ts": $api_login,
    "./routes/index.tsx": $index,
    "./routes/login.tsx": $login,
    "./routes/middleware.tsx": $middleware,
  },
  islands: {
    "./islands/xata.ts": $xata,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
